# Generated by Django 5.2.4 on 2025-07-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('anonse', models.CharField(max_length=250, verbose_name='Описание')),
                ('full_test', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
